function [f,gr,h] = Beta_derive1(x, yobs_tmp, chol_index, Phi_temp, tau_temp,...
                                    Beta_temp, sigmasqalpha, nbasis)
global dimen
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function used for optimization process for coeeficients selected to
% be changed
%
%   Input:
%       1) x - initial values for coeeficient of basis functions need to be
%       optimized 
%       2) yobs_tmp - time series data within the segment
%       3) chol_index - index matrix
%       4) Phi_temp - which component changed
%       5) tau_temp - smoothing parameters  
%       6) Beta_temp - current coefficients
%       7) sigmasqalpha - smoothing parameters for the constant in real
%       components
%       8) nbasis - number of basis function used
%   Main Outputs:
%       1) f - log posterior probability based on input parameters
%       2) gr - gradients for optimization process
%       3) h - hession matrix for optimization process
%
%   Required programs: lin_basis_func
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%initilize Beta_1 and Beta_2: Beta_2 is for imaginary components
nBeta = nbasis + 1;
Beta_1 = zeros(nBeta,(dimen + dimen*(dimen-1)/2));
Beta_2 = zeros(nBeta,dimen*(dimen-1)/2);

select = chol_index(Phi_temp,:).*(1:dimen^2);
select = select(select~=0);

x = reshape(x,nBeta,length(select));
Beta_temp(:,select) = x;
Beta_1(:,:) = Beta_temp(:,1:(dimen + dimen*(dimen-1)/2));
Beta_2(:,:) = Beta_temp(1:nBeta,(dimen + dimen*(dimen-1)/2 + 1): end);

dim = size(yobs_tmp); n = dim(1);
nfreq = floor(n/2); tt = (0:nfreq)/(2*nfreq);
yy = fft(yobs_tmp)/sqrt(n); y = yy(1:(nfreq+1),:); nf = length(y);
[xx_r, xx_i]=lin_basis_func(tt);

%theta's
theta = zeros(dimen*(dimen-1)/2,nf);
for i=1:dimen*(dimen-1)/2
    theta_real = xx_r * Beta_1(:,i+dimen);
    theta_imag = xx_i * Beta_2(:,i);
    theta(i,:) = theta_real + sqrt(-1)*theta_imag;
end    
%delta's
delta_sq = zeros(dimen,nf);
for i=1:dimen
    delta_sq(i,:) = exp(xx_r * Beta_1(:,i));
end   

if dimen==2  %Bivariate Time Series
   if (mod(n,2)==1) %odd n
       f = -sum(log(delta_sq(1,2:end))' + log(delta_sq(2,2:end))' + abs(y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,1)) + ...
           abs(y(2:end,2) - theta(2:end).'.*y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,2))) - ...
           0.5*(log(delta_sq(1,1))' + log(delta_sq(2,1))' + abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1)) + ...
           abs(y(1,2) - theta(1).'.*y(1,1))^2.*exp(-xx_r(1,:)*Beta_1(:,2)));
   else
       f = -sum(log(delta_sq(1,2:nfreq))' + log(delta_sq(2,2:nfreq))' + abs(y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,1)) + ...
           abs(y(2:nfreq,2) - theta(2:nfreq).'.*y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,2))) - ...
           0.5*(log(delta_sq(1,1)) + log(delta_sq(2,1)) + abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1)) + ...
           abs(y(1,2) - theta(1).'.*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))) - ...
           0.5*(log(delta_sq(1,end)) + log(delta_sq(2,end)) + abs(y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,1)) + ...
           abs(y(end,2) - theta(end).'.*y(end,1))^2.*exp(-xx_r(end,:)*Beta_1(:,2)));
   end
   f = f - (0.5.*(Beta_1(1,1)* Beta_1(1,1)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,1)'*Beta_1(2:nBeta,1))/tau_temp(1))*chol_index(Phi_temp,1) -...
           (0.5.*(Beta_1(1,2)* Beta_1(1,2)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,2)'*Beta_1(2:nBeta,2))/tau_temp(2))*chol_index(Phi_temp,2) -...
           (0.5.*(Beta_1(1,3)* Beta_1(1,3)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,3)'*Beta_1(2:nBeta,3))/tau_temp(3))*chol_index(Phi_temp,3) -...
           (0.5.*(Beta_2(1:nBeta,1)'*Beta_2(1:nBeta,1))/tau_temp(4))*chol_index(Phi_temp,4);

    gr1 = zeros(nBeta,1); gr2 = zeros(nBeta,1); gr3 = zeros(nBeta,1); gr4 = zeros(nBeta,1);
    gr1(1) = Beta_1(1,1)/sigmasqalpha; gr1(2:nBeta,1) = Beta_1(2:nBeta,1)/tau_temp(1);
    gr2(1) = Beta_1(1,2)/sigmasqalpha; gr2(2:nBeta,1) = Beta_1(2:nBeta,2)/tau_temp(2);
    gr3(1) = Beta_1(1,3)/sigmasqalpha; gr3(2:nBeta,1) = Beta_1(2:nBeta,3)/tau_temp(3);
    gr4(1:nBeta,1) = Beta_2(1:nBeta,1)/tau_temp(4);
    h11(1,1)=1/sigmasqalpha; h11(2:nBeta,2:nBeta)=1/tau_temp(1)*eye(nbasis);
    h22(1,1)=1/sigmasqalpha; h22(2:nBeta,2:nBeta)= 1/tau_temp(2)*eye(nbasis);
    h33(1,1)=1/sigmasqalpha; h33(2:nBeta,2:nBeta)= 1/tau_temp(3)*eye(nbasis);
    h44(1:nBeta,1:nBeta)=1/tau_temp(4)*eye(nBeta);
    h42 = zeros(nBeta,nBeta); h32 = zeros(nBeta,nBeta);

    if (mod(n,2)==1)     
        %%%%%%%%%%%%%%%%%%%%%%%%
        %gradient
        %%%%%%%%%%%%%%%%%%%%%%%%
        rk = -y(2:end,1).*conj(y(2:end,2)) - y(2:end,2).*conj(y(2:end,1));
        ik = sqrt(-1)*(-y(2:end,1).*conj(y(2:end,2)) + y(2:end,2).*conj(y(2:end,1)));
        ck = 2*abs(y(2:end,1)).^2;
    
        gr1 = gr1 + xx_r(2:end,:)'*(1-abs(y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,1))) + ...
                    0.5*(xx_r(1,:)'*(1-abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))));
        gr2 = gr2 + xx_r(2:end,:)'*(1 - abs(y(2:end,2)-theta(2:end).'.*y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,2))) + ...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,2)-theta(1).'.*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))));  
        temp_mat_31 = bsxfun(@times, xx_r(2:end,:),rk);
        temp_mat_32 = bsxfun(@times, ck, bsxfun(@times, xx_r(2:end,:),xx_r(2:end,:)*Beta_1(:,3)));
        gr3 = gr3 + sum( bsxfun(@times, (temp_mat_31+temp_mat_32), exp(-xx_r(2:end,:)*Beta_1(:,2)) ))' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)');
        temp_mat_41 = bsxfun(@times, ik, xx_i(2:end,:));
        temp_mat_42 = bsxfun(@times, ck, bsxfun(@times,xx_i(2:end,:),xx_i(2:end,:)*Beta_2(:,1)));
        gr4 = gr4 + sum( bsxfun(@times, (temp_mat_41 + temp_mat_42), exp(-xx_r(2:end,:)*Beta_1(:,2))))' + ...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(sqrt(-1)*(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)');
        %%%%%%%%%%%%%%%%%%%
        %hession
        %%%%%%%%%%%%%%%%%%%
        bigmat_h11 = kron(bsxfun(@times, abs(y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,1)), xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h11 = repmat(xx_r(2:end,:), 1,nBeta);
        h11 = h11 + reshape(sum(bsxfun(@times, bigmat_h11, coefmat_h11),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))*xx_r(1,:)'*xx_r(1,:));
    
        bigmat_h22 = kron(bsxfun(@times,  abs(y(2:end,2)-theta(2:end).'.*y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,2)),...
                                                                xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h22 = repmat(xx_r(2:end,:), 1,nBeta);
        h22 = h22 + reshape(sum(bsxfun(@times, bigmat_h22, coefmat_h22),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,2)-theta(1).'.*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))*xx_r(1,:)'*xx_r(1,:));
    
        bigmat_h33 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck, xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h33 = repmat(xx_r(2:end,:), 1,nBeta);         
        h33 = h33 + reshape(sum(bsxfun(@times, bigmat_h33, coefmat_h33),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:));


        bigmat_h44 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck, xx_i(2:end,:)),ones(nBeta,1)');
        coefmat_h44 = repmat(xx_i(2:end,:), 1,nBeta);         
        h44 = h44 + reshape(sum(bsxfun(@times, bigmat_h44, coefmat_h44),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:));
    
        bigmat_h42_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck.*(xx_i(2:end,:)*Beta_2(:,1)),...
                        xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h42_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h42_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,2)).*ik, xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h42_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        h42 = h42 + reshape(sum(bsxfun(@times, bigmat_h42_1, coefmat_h42_1) +...
                    bsxfun(@times, bigmat_h42_2, coefmat_h42_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)+...
                    sqrt(-1)*(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1)))*xx_i(1,:))'*xx_r(1,:));

        bigmat_h32_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck.*(xx_r(2:end,:)*Beta_1(:,3)),...
                       xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h32_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h32_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,2)).*rk, xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h32_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        h32 = h32 + reshape(sum(bsxfun(@times, bigmat_h32_1, coefmat_h32_1) +...
                    bsxfun(@times, bigmat_h32_2, coefmat_h32_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:))'*xx_r(1,:));      
        h24=h42'; h23=h32';
    else
        %%%%%%%%%%%%%%%%%%%%%
        %gradient
        %%%%%%%%%%%%%%%%%%%%%
        rk = -y(2:nfreq,1).*conj(y(2:nfreq,2)) - y(2:nfreq,2).*conj(y(2:nfreq,1));
        ik = sqrt(-1)*(-y(2:nfreq,1).*conj(y(2:nfreq,2)) + y(2:nfreq,2).*conj(y(2:nfreq,1)));
        ck = 2*abs(y(2:nfreq,1)).^2;
    
        gr1 = gr1 + xx_r(2:nfreq,:)'*(1-abs(y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,1))) + ...
                    0.5*(xx_r(1,:)'*(1-abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1)))) +...
                    0.5*(xx_r(end,:)'*(1-abs(y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,1))));
        gr2 = gr2 + xx_r(2:nfreq,:)'*(1 - abs(y(2:nfreq,2)-theta(2:nfreq).'.*y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,2))) + ...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,2)-theta(1).'.*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2)))) + ...
                    0.5*(xx_r(end,:)'*(1 - abs(y(end,2)-theta(end).'.*y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,2))));  
        temp_mat_31 = bsxfun(@times,rk, xx_r(2:nfreq,:));
        temp_mat_32 = bsxfun(@times,ck,bsxfun(@times, xx_r(2:nfreq,:),xx_r(2:nfreq,:)*Beta_1(:,3)));
        gr3 = gr3 + sum( bsxfun(@times, (temp_mat_31 + temp_mat_32), exp(-xx_r(2:nfreq,:)*Beta_1(:,2)) ))' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)') +...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(-y(end,1).*conj(y(end,2)) - y(end,2).*conj(y(end,1)))*xx_r(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,3))*xx_r(end,:)');
        temp_mat_41 = bsxfun(@times, ik, xx_i(2:nfreq,:));
        temp_mat_42 = bsxfun(@times, ck, bsxfun(@times,xx_i(2:nfreq,:),xx_i(2:nfreq,:)*Beta_2(:,1)));
        gr4 = gr4 + sum( bsxfun(@times, (temp_mat_41 + temp_mat_42), exp(-xx_r(2:nfreq,:)*Beta_1(:,2))))' + ...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(sqrt(-1)*(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)') +...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(sqrt(-1)*(-y(end,1).*conj(y(end,2)) + y(end,2).*conj(y(end,1))))*xx_i(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,1))*xx_i(end,:)');
        %%%%%%%%%%%%%%%%%%%
        %hession
        %%%%%%%%%%%%%%%%%%%
        bigmat_h11 = kron(bsxfun(@times, abs(y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,1)), xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h11 = repmat(xx_r(2:nfreq,:), 1,nBeta);
        h11 = h11 + reshape(sum(bsxfun(@times, bigmat_h11, coefmat_h11),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(abs(y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,1))*xx_r(end,:)'*xx_r(end,:));
    
        bigmat_h22 = kron(bsxfun(@times,  abs(y(2:nfreq,2)-theta(2:nfreq).'.*y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,2)),...
                                                                xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h22 = repmat(xx_r(2:nfreq,:), 1,nBeta);
        h22 = h22 + reshape(sum(bsxfun(@times, bigmat_h22, coefmat_h22),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,2)-theta(1).'.*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(abs(y(end,2)-theta(end).'.*y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,2))*xx_r(end,:)'*xx_r(end,:));
    
        bigmat_h33 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck, xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h33 = repmat(xx_r(2:nfreq,:), 1,nBeta);         
        h33 = h33 + reshape(sum(bsxfun(@times, bigmat_h33, coefmat_h33),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*xx_r(end,:)'*xx_r(end,:));

        bigmat_h44 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck, xx_i(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h44 = repmat(xx_i(2:nfreq,:), 1,nBeta);         
        h44 = h44 + reshape(sum(bsxfun(@times, bigmat_h44, coefmat_h44),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*xx_i(end,:)'*xx_i(end,:));
    
        bigmat_h42_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck.*(xx_i(2:nfreq,:)*Beta_2(:,1)),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h42_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h42_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ik, xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h42_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        h42 = h42 + reshape(sum(bsxfun(@times, bigmat_h42_1, coefmat_h42_1) +...
                    bsxfun(@times, bigmat_h42_2, coefmat_h42_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)+...
                    sqrt(-1)*(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1)))*xx_i(1,:))'*xx_r(1,:)) +...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,1))*xx_i(end,:)+...
                    sqrt(-1)*(-y(end,1).*conj(y(end,2)) + y(end,2).*conj(y(end,1)))*xx_i(end,:))'*xx_r(end,:));

        bigmat_h32_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck.*(xx_r(2:nfreq,:)*Beta_1(:,3)),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h32_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h32_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*rk, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h32_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        h32 = h32 + reshape(sum(bsxfun(@times, bigmat_h32_1, coefmat_h32_1) +...
                    bsxfun(@times, bigmat_h32_2, coefmat_h32_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:))'*xx_r(1,:)) +...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,3))*xx_r(end,:)+...
                    (-y(end,1).*conj(y(end,2)) - y(end,2).*conj(y(end,1)))*xx_r(end,:))'*xx_r(end,:));
        h24=h42'; h23=h32';
    end   
    h1 = [h11,zeros(nBeta,2*nBeta+nBeta)];
    h2 = [zeros(nBeta,nBeta),h22,-h23,-h24];
    h3 = [zeros(nBeta,nBeta),-h32,h33,zeros(nBeta,nBeta)];
    h4 = [zeros(nBeta,nBeta),-h42,zeros(nBeta,nBeta),h44];    
    gr = [gr1;gr2;gr3;gr4]; h = [h1;h2;h3;h4]; f = -f; 
    gr_index = (1:(4*nBeta)).*[kron(chol_index(Phi_temp,1:3),ones(nBeta,1)'), kron(chol_index(Phi_temp,4),ones(nBeta,1)')];
    gr_index = gr_index(find(gr_index~=0));
    gr = gr(gr_index); h = h(gr_index,gr_index); 
    
elseif dimen==3
    
    if (mod(n,2)==1) %odd n
        f = -sum(log(delta_sq(1,2:end))' + log(delta_sq(2,2:end))' + log(delta_sq(3,2:end))' + ...
                    conj(y(2:end,1)).*y(2:end,1).*exp(-xx_r(2:end,:)*Beta_1(:,1)) + ...
                    conj(y(2:end,2) - theta(1,2:end).'.*y(2:end,1)).*(y(2:end,2) - theta(1,2:end).'.*y(2:end,1)).*exp(-xx_r(2:end,:)*Beta_1(:,2))+...
                    conj(y(2:end,3) -(theta(2,2:end).'.*y(2:end,1)+ theta(3,2:end).'.*y(2:end,2))).*(y(2:end,3) -(theta(2,2:end).'.*y(2:end,1)+ theta(3,2:end).'.*y(2:end,2))).*...
                    exp(-xx_r(2:end,:)*Beta_1(:,3))) - ...
                    0.5*(log(delta_sq(1,1))' + log(delta_sq(2,1))' + log(delta_sq(3,1))' + ...
                    conj(y(1,1)).*y(1,1).*exp(-xx_r(1,:)*Beta_1(:,1)) + ...
                    conj(y(1,2) - theta(1,1).'.*y(1,1)).*(y(1,2) - theta(1,1).'.*y(1,1)).*exp(-xx_r(1,:)*Beta_1(:,2))+...
                    conj(y(1,3) -(theta(2,1).'.*y(1,1)+ theta(3,1).'.*y(1,2))).*(y(1,3) -(theta(2,1).'.*y(1,1)+ theta(3,1).'.*y(1,2))).*...
                    exp(-xx_r(1,:)*Beta_1(:,3)));
    else
        f = -sum(log(delta_sq(1,2:nfreq))' + log(delta_sq(2,2:nfreq))' + log(delta_sq(3,2:nfreq))' + ...
                    conj(y(2:nfreq,1)).*y(2:nfreq,1).*exp(-xx_r(2:nfreq,:)*Beta_1(:,1)) + ...
                    conj(y(2:nfreq,2) - theta(1,2:nfreq).'.*y(2:nfreq,1)).*(y(2:nfreq,2) - theta(1,2:nfreq).'.*y(2:nfreq,1)).*exp(-xx_r(2:nfreq,:)*Beta_1(:,2))+...
                    conj(y(2:nfreq,3) -(theta(2,2:nfreq).'.*y(2:nfreq,1)+ theta(3,2:nfreq).'.*y(2:nfreq,2))).*(y(2:nfreq,3) -(theta(2,2:nfreq).'.*y(2:nfreq,1)+ theta(3,2:nfreq).'.*y(2:nfreq,2))).*...
                    exp(-xx_r(2:nfreq,:)*Beta_1(:,3))) - ...
                    0.5*(log(delta_sq(1,1))' + log(delta_sq(2,1))' + log(delta_sq(3,1))' + ...
                    conj(y(1,1)).*y(1,1).*exp(-xx_r(1,:)*Beta_1(:,1)) + ...
                    conj(y(1,2) - theta(1,1).'.*y(1,1)).*(y(1,2) - theta(1,1).'.*y(1,1)).*exp(-xx_r(1,:)*Beta_1(:,2))+...
                    conj(y(1,3) -(theta(2,1).'.*y(1,1)+ theta(3,1).'.*y(1,2))).*(y(1,3) -(theta(2,1).'.*y(1,1)+ theta(3,1).'.*y(1,2))).*...
                    exp(-xx_r(1,:)*Beta_1(:,3)))-...
                    0.5*(log(delta_sq(1,end))' + log(delta_sq(2,end))' + log(delta_sq(3,end))' + ...
                    conj(y(end,1)).*y(end,1).*exp(-xx_r(end,:)*Beta_1(:,1)) + ...
                    conj(y(end,2) - theta(1,end).'.*y(end,1)).*(y(end,2) - theta(1,end).'.*y(end,1)).*exp(-xx_r(end,:)*Beta_1(:,2))+...
                    conj(y(end,3) -(theta(2,end).'.*y(end,1)+ theta(3,end).'.*y(end,2))).*(y(end,3) -(theta(2,end).'.*y(end,1)+ theta(3,end).'.*y(end,2))).*...
                    exp(-xx_r(end,:)*Beta_1(:,3)));
    end
    f = f - (0.5.*(Beta_1(1,1)* Beta_1(1,1)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,1)'*Beta_1(2:nBeta,1))/tau_temp(1))*chol_index(Phi_temp,1) -...
            (0.5.*(Beta_1(1,2)* Beta_1(1,2)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,2)'*Beta_1(2:nBeta,2))/tau_temp(2))*chol_index(Phi_temp,2) -...
            (0.5.*(Beta_1(1,3)* Beta_1(1,3)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,3)'*Beta_1(2:nBeta,3))/tau_temp(3))*chol_index(Phi_temp,3) -...
            (0.5.*(Beta_1(1,4)* Beta_1(1,4)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,4)'*Beta_1(2:nBeta,4))/tau_temp(4))*chol_index(Phi_temp,4) -...
            (0.5.*(Beta_1(1,5)* Beta_1(1,5)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,5)'*Beta_1(2:nBeta,5))/tau_temp(5))*chol_index(Phi_temp,5) -...
            (0.5.*(Beta_1(1,6)* Beta_1(1,6)')/sigmasqalpha + 0.5.*(Beta_1(2:nBeta,6)'*Beta_1(2:nBeta,6))/tau_temp(6))*chol_index(Phi_temp,6) -...
            (0.5.*(Beta_2(1:nBeta,1)'*Beta_2(1:nBeta,1))/tau_temp(7))*chol_index(Phi_temp,7)-...
            (0.5.*(Beta_2(1:nBeta,2)'*Beta_2(1:nBeta,2))/tau_temp(8))*chol_index(Phi_temp,8)-...
            (0.5.*(Beta_2(1:nBeta,3)'*Beta_2(1:nBeta,3))/tau_temp(9))*chol_index(Phi_temp,9);
    

    gr1 = zeros(nBeta,1); gr2 = zeros(nBeta,1); gr3 = zeros(nBeta,1); gr4 = zeros(nBeta,1);
    gr5 = zeros(nBeta,1); gr6 = zeros(nBeta,1); gr7 = zeros(nBeta,1); gr8 = zeros(nBeta,1);
    gr9 = zeros(nBeta,1);

    gr1(1) = Beta_1(1,1)/sigmasqalpha; gr1(2:nBeta) = Beta_1(2:nBeta,1)/tau_temp(1);
    gr2(1) = Beta_1(1,2)/sigmasqalpha; gr2(2:nBeta) = Beta_1(2:nBeta,2)/tau_temp(2);
    gr3(1) = Beta_1(1,3)/sigmasqalpha; gr3(2:nBeta) = Beta_1(2:nBeta,3)/tau_temp(3);
    gr4(1) = Beta_1(1,4)/sigmasqalpha; gr4(2:nBeta) = Beta_1(2:nBeta,4)/tau_temp(4);
    gr5(1) = Beta_1(1,5)/sigmasqalpha; gr5(2:nBeta) = Beta_1(2:nBeta,5)/tau_temp(5);
    gr6(1) = Beta_1(1,6)/sigmasqalpha; gr6(2:nBeta) = Beta_1(2:nBeta,6)/tau_temp(6);
    gr7(1:nBeta) = Beta_2(1:nBeta,1)/tau_temp(7);
    gr8(1:nBeta) = Beta_2(1:nBeta,2)/tau_temp(8);
    gr9(1:nBeta) = Beta_2(1:nBeta,3)/tau_temp(9);

    h11(1,1)=1/sigmasqalpha; h11(2:nBeta,2:nBeta)=1/tau_temp(1)*eye(nbasis);
    h22(1,1)=1/sigmasqalpha; h22(2:nBeta,2:nBeta)= 1/tau_temp(2)*eye(nbasis);
    h33(1,1)=1/sigmasqalpha; h33(2:nBeta,2:nBeta)= 1/tau_temp(3)*eye(nbasis);
    h44(1,1)=1/sigmasqalpha; h44(2:nBeta,2:nBeta)=1/tau_temp(4)*eye(nbasis);
    h55(1,1)=1/sigmasqalpha; h55(2:nBeta,2:nBeta)= 1/tau_temp(5)*eye(nbasis);
    h66(1,1)=1/sigmasqalpha; h66(2:nBeta,2:nBeta)= 1/tau_temp(6)*eye(nbasis);
    h77(1:nBeta,1:nBeta)=1/tau_temp(7)*eye(nBeta);
    h88(1:nBeta,1:nBeta)=1/tau_temp(8)*eye(nBeta);
    h99(1:nBeta,1:nBeta)=1/tau_temp(9)*eye(nBeta);

    h42 = zeros(nBeta,nBeta);
    h53 = zeros(nBeta,nBeta);
    h56 = zeros(nBeta,nBeta);
    h59 = zeros(nBeta,nBeta);
    h63 = zeros(nBeta,nBeta); 
    h68 = zeros(nBeta,nBeta);
    h72 = zeros(nBeta,nBeta);
    h83 = zeros(nBeta,nBeta);
    h93 = zeros(nBeta,nBeta);
    h98 = zeros(nBeta,nBeta);
    if (mod(n,2)==1)     
        %%%%%%%%%%%%%%%%%%%%%%%%
        %gradient
        %%%%%%%%%%%%%%%%%%%%%%%%
        rk4 = -y(2:end,1).*conj(y(2:end,2)) - y(2:end,2).*conj(y(2:end,1));
        ck4 = 2*abs(y(2:end,1)).^2;
        rk5 = -y(2:end,1).*conj(y(2:end,3)) - y(2:end,3).*conj(y(2:end,1));
        ck5 = 2*abs(y(2:end,1)).^2;
        b = theta(3,:);
        dk5 =  y(2:end,2).*conj(y(2:end,1)).*(b(2:end).') + conj(y(2:end,2)).*y(2:end,1).*conj(b(2:end).');
        rk6 = -y(2:end,2).*conj(y(2:end,3)) - y(2:end,3).*conj(y(2:end,2));
        ck6 = 2*abs(y(2:end,2)).^2;
        a = theta(2,:);
        dk6 =  y(2:end,1).*conj(y(2:end,2)).*(a(2:end).') + conj(y(2:end,1)).*y(2:end,2).*conj(a(2:end).');
        ik7 = sqrt(-1)*(-y(2:end,1).*conj(y(2:end,2)) + y(2:end,2).*conj(y(2:end,1)));
        ck7 = 2*abs(y(2:end,1)).^2;
        ik8 = sqrt(-1)*(-y(2:end,1).*conj(y(2:end,3)) + y(2:end,3).*conj(y(2:end,1)));
        ck8 = 2*abs(y(2:end,1)).^2;
        dk8 = sqrt(-1)*(-y(2:end,2).*conj(y(2:end,1)).*(b(2:end).') + conj(y(2:end,2).*conj(y(2:end,1)).*(b(2:end).'))) ;
        ik9 = sqrt(-1)*(-y(2:end,2).*conj(y(2:end,3)) + y(2:end,3).*conj(y(2:end,2)));
        ck9 = 2*abs(y(2:end,2)).^2;
        dk9 = sqrt(-1)*(-y(2:end,1).*conj(y(2:end,2)).*(a(2:end).') + conj(y(2:end,1).*conj(y(2:end,2)).*(a(2:end).'))) ;
    
        gr1 = gr1 + xx_r(2:end,:)'*(1-abs(y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,1))) + ...
                    0.5*(xx_r(1,:)'*(1-abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))));
        gr2 = gr2 + xx_r(2:end,:)'*(1 - abs(y(2:end,2)-theta(1,2:end).'.*y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,2))) + ...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,2)-theta(1,1).*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))));  
        gr3 = gr3 + xx_r(2:end,:)'*(1 - abs(y(2:end,3) - theta(2,2:end).'.*y(2:end,1) - theta(3,2:end).'.*y(2:end,2)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,3)))+...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,3) - theta(2,1).*y(1,1) - theta(3,1).*y(1,2))^2.*exp(-xx_r(1,:)*Beta_1(:,3))));             
        temp_mat_41 = bsxfun(@times, xx_r(2:end,:),rk4);
        temp_mat_42 = bsxfun(@times, ck4, bsxfun(@times, xx_r(2:end,:),xx_r(2:end,:)*Beta_1(:,4)));
        gr4 = gr4 + sum( bsxfun(@times, (temp_mat_41+temp_mat_42), exp(-xx_r(2:end,:)*Beta_1(:,2)) ))' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,4))*xx_r(1,:)');
        temp_mat_51 = bsxfun(@times, xx_r(2:end,:),rk5);
        temp_mat_52 = bsxfun(@times, ck5, bsxfun(@times, xx_r(2:end,:),xx_r(2:end,:)*Beta_1(:,5))); 
        temp_mat_53 = bsxfun(@times, xx_r(2:end,:),dk5);
        gr5 = gr5 + sum( bsxfun(@times, (temp_mat_51 + temp_mat_52 + temp_mat_53), exp(-xx_r(2:end,:)*Beta_1(:,3)) ))'+...
                    0.5* ( exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,3)) - y(1,3).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,5))*xx_r(1,:)'+...
                    exp(-xx_r(1,:)*Beta_1(:,3))*(y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_r(1,:)');
        temp_mat_61 = bsxfun(@times, xx_r(2:end,:),rk6);
        temp_mat_62 = bsxfun(@times, ck6, bsxfun(@times, xx_r(2:end,:),xx_r(2:end,:)*Beta_1(:,6))); 
        temp_mat_63 = bsxfun(@times, xx_r(2:end,:),dk6);
        gr6 = gr6 + sum(bsxfun(@times, (temp_mat_61 + temp_mat_62 + temp_mat_63), exp(-xx_r(2:end,:)*Beta_1(:,3)) ))'+...
                    0.5* (exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,2).*conj(y(1,3)) - y(1,3).*conj(y(1,2)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*(xx_r(1,:)*Beta_1(:,6))*xx_r(1,:)'+...
                    exp(-xx_r(1,:)*Beta_1(:,3))*(y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_r(1,:)');
        temp_mat_71 = bsxfun(@times, ik7, xx_i(2:end,:));
        temp_mat_72 = bsxfun(@times, ck7, bsxfun(@times,xx_i(2:end,:),xx_i(2:end,:)*Beta_2(:,1)));
        gr7 = gr7 + sum( bsxfun(@times, (temp_mat_71 + temp_mat_72), exp(-xx_r(2:end,:)*Beta_1(:,2))))' + ...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(imag(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)');
        temp_mat_81 = bsxfun(@times, ik8, xx_i(2:end,:));
        temp_mat_82 = bsxfun(@times, ck8, bsxfun(@times,xx_i(2:end,:),xx_i(2:end,:)*Beta_2(:,2)));      
        temp_mat_83 = bsxfun(@times, xx_i(2:end,:),dk8);
        gr8 = gr8 + sum( bsxfun(@times, (temp_mat_81 + temp_mat_82 + temp_mat_83), exp(-xx_r(2:end,:)*Beta_1(:,3))))' + ...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(imag(-y(1,1).*conj(y(1,3)) + y(1,3).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,2))*xx_i(1,:)'+...
                    sqrt(-1)*exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,2)).*(b(1).') + conj(y(1,1).*conj(y(1,2)).*(b(1).')))*xx_i(1,:)');
        temp_mat_91 = bsxfun(@times, ik9, xx_i(2:end,:));
        temp_mat_92 = bsxfun(@times, ck9, bsxfun(@times,xx_i(2:end,:),xx_i(2:end,:)*Beta_2(:,3)));      
        temp_mat_93 = bsxfun(@times, xx_i(2:end,:),dk9);
        gr9 = gr9 + sum( bsxfun(@times, (temp_mat_91 + temp_mat_92 + temp_mat_93), exp(-xx_r(2:end,:)*Beta_1(:,3))))' + ...
                    0.5 * (exp(-xx_r(1,:)*Beta_1(:,3))*(imag(-y(1,2).*conj(y(1,3)) + y(1,3).*conj(y(1,2))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*(xx_i(1,:)*Beta_2(:,3))*xx_i(1,:)'+...
                    sqrt(-1)*exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_i(1,:)');     
        %%%%%%%%%%%%%%%%%%%
        %hession
        %%%%%%%%%%%%%%%%%%%
        bigmat_h11 = kron(bsxfun(@times, abs(y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,1)), xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h11 = repmat(xx_r(2:end,:), 1,nBeta);
        h11 = h11 + reshape(sum(bsxfun(@times, bigmat_h11, coefmat_h11),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))*xx_r(1,:)'*xx_r(1,:));
    
        bigmat_h22 = kron(bsxfun(@times,  abs(y(2:end,2)-theta(1,2:end).'.*y(2:end,1)).^2.*exp(-xx_r(2:end,:)*Beta_1(:,2)),xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h22 = repmat(xx_r(2:end,:), 1,nBeta);
        h22 = h22 + reshape(sum(bsxfun(@times, bigmat_h22, coefmat_h22),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,2)-theta(1,1).*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))*xx_r(1,:)'*xx_r(1,:));
        
        bigmat_h33 = kron(bsxfun(@times,  abs(y(2:end,3) - theta(2,2:end).'.*y(2:end,1) - theta(3,2:end).'.*y(2:end,2)).^2.*...
                        exp(-xx_r(2:end,:)*Beta_1(:,3)),xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h33 = repmat(xx_r(2:end,:), 1,nBeta);
        h33 = h33 + reshape(sum(bsxfun(@times, bigmat_h33, coefmat_h33),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,3) - theta(2,1).'.*y(1,1) - theta(3,1).'.*y(1,2)).^2.*...
                    exp(-xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)'*xx_r(1,:));        
        
        bigmat_h44 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck4, xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h44 = repmat(xx_r(2:end,:), 1,nBeta);         
        h44 = h44 + reshape(sum(bsxfun(@times, bigmat_h44, coefmat_h44),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:));

        bigmat_h55 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck5, xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h55 = repmat(xx_r(2:end,:), 1,nBeta);         
        h55 = h55 + reshape(sum(bsxfun(@times, bigmat_h55, coefmat_h55),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:));
            
        bigmat_h66 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck6, xx_r(2:end,:)),ones(nBeta,1)');
        coefmat_h66 = repmat(xx_r(2:end,:), 1,nBeta);         
        h66 = h66 + reshape(sum(bsxfun(@times, bigmat_h66, coefmat_h66),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*xx_r(1,:)'*xx_r(1,:));            
                 
        bigmat_h77 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck7, xx_i(2:end,:)),ones(nBeta,1)');
        coefmat_h77 = repmat(xx_i(2:end,:), 1,nBeta);         
        h77 = h77 + reshape(sum(bsxfun(@times, bigmat_h77, coefmat_h77),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:));
    
        bigmat_h88 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck8, xx_i(2:end,:)),ones(nBeta,1)');
        coefmat_h88 = repmat(xx_i(2:end,:), 1,nBeta);         
        h88 = h88 + reshape(sum(bsxfun(@times, bigmat_h88, coefmat_h88),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:));        
            
        bigmat_h99 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck9, xx_i(2:end,:)),ones(nBeta,1)');
        coefmat_h99 = repmat(xx_i(2:end,:), 1,nBeta);         
        h99 = h99 + reshape(sum(bsxfun(@times, bigmat_h99, coefmat_h99),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*xx_i(1,:)'*xx_i(1,:));              
              
        bigmat_h42_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck4.*(xx_r(2:end,:)*Beta_1(:,4)),...
                        xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h42_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h42_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,2)).*rk4, xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h42_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        h42 = h42 + reshape(sum(bsxfun(@times, bigmat_h42_1, coefmat_h42_1) +...
                    bsxfun(@times, bigmat_h42_2, coefmat_h42_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,4))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:))'*xx_r(1,:));      

        bigmat_h53_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck5.*(xx_r(2:end,:)*Beta_1(:,5)),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h53_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h53_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*rk5, xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h53_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h53_3 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*dk5, xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h53_3 = repmat(xx_r(2:end,:), 1,nBeta);      
        h53 = h53 + reshape(sum(bsxfun(@times, bigmat_h53_1, coefmat_h53_1) +...
                    bsxfun(@times, bigmat_h53_2, coefmat_h53_2)+...
                    bsxfun(@times, bigmat_h53_3, coefmat_h53_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,5))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,3)) - y(1,3).*conj(y(1,1)))*xx_r(1,:)+...
                    (y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_r(1,:))'*xx_r(1,:));  
                    
        bigmat_h56_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,1)).*y(2:end,2),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h56_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h56_2 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,2)).*y(2:end,1),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h56_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        h56 = real(h56 + reshape(sum(bsxfun(@times, bigmat_h56_1, coefmat_h56_1) +...
                        bsxfun(@times, bigmat_h56_2, coefmat_h56_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_r(1,:)+...
                        (conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_r(1,:))));     
                    
        bigmat_h59_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,1)).*y(2:end,2),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h59_1 = repmat(xx_i(2:end,:), 1,nBeta);  
        bigmat_h59_2 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,2)).*y(2:end,1),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h59_2 = repmat(xx_i(2:end,:), 1,nBeta);  
        h59 = imag(h59 + reshape(sum(bsxfun(@times, bigmat_h59_1, coefmat_h59_1) -...
                        bsxfun(@times, bigmat_h59_2, coefmat_h59_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_i(1,:) -...
                        (conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_i(1,:))));                      
    
        bigmat_h63_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck6.*(xx_r(2:end,:)*Beta_1(:,6)),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h63_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h63_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*rk6, xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h63_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h63_3 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*dk6 , xx_r(2:end,:)), ones(nBeta,1)');
        coefmat_h63_3 = repmat(xx_r(2:end,:), 1,nBeta);      
        h63 = h63 + reshape(sum(bsxfun(@times, bigmat_h63_1, coefmat_h63_1) +...
                    bsxfun(@times, bigmat_h63_2, coefmat_h63_2)+...
                    bsxfun(@times, bigmat_h63_3, coefmat_h63_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,2)).^2*(xx_r(1,:)*Beta_1(:,6))*xx_r(1,:)+...
                    (-y(1,2).*conj(y(1,3)) - y(1,3).*conj(y(1,2)))*xx_r(1,:)+...
                    (y(1,2).*conj(y(1,1)).*(a(1).') + conj(y(1,2).*conj(y(1,1)).*(a(1).')))*xx_r(1,:))'*xx_r(1,:));                  

        bigmat_h68_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,2)).*y(2:end,1),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h68_1 = repmat(xx_i(2:end,:), 1,nBeta);  
        bigmat_h68_2 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,1)).*y(2:end,2),...
                        xx_r(2:end,:)), ones(nBeta,1)');     
        coefmat_h68_2 = repmat(xx_i(2:end,:), 1,nBeta);  
        h68 = imag(h68 + reshape(sum(bsxfun(@times, bigmat_h68_1, coefmat_h68_1) -...
                        bsxfun(@times, bigmat_h68_2, coefmat_h68_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_i(1,:)-...
                        (conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_i(1,:))));
                    
        bigmat_h72_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,2)).*ck7.*(xx_i(2:end,:)*Beta_2(:,1)),...
                        xx_i(2:end,:)), ones(nBeta,1)');                
        coefmat_h72_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h72_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,2)).*ik7, xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h72_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        h72 = h72 + reshape(sum(bsxfun(@times, bigmat_h72_1, coefmat_h72_1) +...
                    bsxfun(@times, bigmat_h72_2, coefmat_h72_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)+...
                    imag(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1)))*xx_i(1,:))'*xx_r(1,:));     
    
        bigmat_h83_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck8.*(xx_i(2:end,:)*Beta_2(:,2)),...
                        xx_i(2:end,:)), ones(nBeta,1)');     
        coefmat_h83_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h83_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*ik8, xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h83_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h83_3 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*(dk8), xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h83_3 = repmat(xx_r(2:end,:), 1,nBeta);      
        h83 = h83 + reshape(sum(bsxfun(@times, bigmat_h83_1, coefmat_h83_1) +...
                    bsxfun(@times, bigmat_h83_2, coefmat_h83_2)+...
                    bsxfun(@times, bigmat_h83_3, coefmat_h83_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,2))*xx_i(1,:)+...
                    (-y(1,1).*conj(y(1,3)) + y(1,3).*conj(y(1,1)))*xx_i(1,:)+...
                    imag(-y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_i(1,:))'*xx_r(1,:));           
                    
        bigmat_h93_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*ck9.*(xx_i(2:end,:)*Beta_2(:,3)),...
                        xx_i(2:end,:)), ones(nBeta,1)');     
        coefmat_h93_1 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h93_2 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*ik9, xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h93_2 = repmat(xx_r(2:end,:), 1,nBeta);  
        bigmat_h93_3 = kron(bsxfun(@times,exp(-xx_r(2:end,:)*Beta_1(:,3)).*(dk9), xx_i(2:end,:)), ones(nBeta,1)');
        coefmat_h93_3 = repmat(xx_r(2:end,:), 1,nBeta);      
        h93 = h93 + reshape(sum(bsxfun(@times, bigmat_h93_1, coefmat_h93_1) +...
                    bsxfun(@times, bigmat_h93_2, coefmat_h93_2)+...
                    bsxfun(@times, bigmat_h93_3, coefmat_h93_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,2)).^2*(xx_i(1,:)*Beta_2(:,3))*xx_i(1,:)+...
                    (-y(1,2).*conj(y(1,3)) + y(1,3).*conj(y(1,2)))*xx_i(1,:)+...
                    imag(-y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_i(1,:))'*xx_r(1,:));     

        bigmat_h98_1 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,1)).*y(2:end,2),...
                        xx_i(2:end,:)), ones(nBeta,1)');     
        coefmat_h98_1 = repmat(xx_i(2:end,:), 1,nBeta);  
        bigmat_h98_2 = kron(bsxfun(@times, exp(-xx_r(2:end,:)*Beta_1(:,3)).*conj(y(2:end,2)).*y(2:end,1),...
                        xx_i(2:end,:)), ones(nBeta,1)');     
        coefmat_h98_2 = repmat(xx_i(2:end,:), 1,nBeta);  
        h98 = real(h98 + reshape(sum(bsxfun(@times, bigmat_h98_1, coefmat_h98_1) +...
                        bsxfun(@times, bigmat_h98_2, coefmat_h98_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_i(1,:)'*xx_i(1,:)+...
                        (conj(y(1,2)).*y(1,1))*xx_i(1,:)'*xx_i(1,:))));    
                    
        h24=h42'; h35=h53'; h65=h56'; h95=h59'; h36=h63';
        h86=h68'; h27=h72'; h38=h83'; h39=h93'; h89=h98';
    else
        %%%%%%%%%%%%%%%%%%%%%%%%
        %gradient
        %%%%%%%%%%%%%%%%%%%%%%%%
        rk4 = -y(2:nfreq,1).*conj(y(2:nfreq,2)) - y(2:nfreq,2).*conj(y(2:nfreq,1));
        ck4 = 2*abs(y(2:nfreq,1)).^2;
        rk5 = -y(2:nfreq,1).*conj(y(2:nfreq,3)) - y(2:nfreq,3).*conj(y(2:nfreq,1));
        ck5 = 2*abs(y(2:nfreq,1)).^2;
        b = theta(3,:);
        dk5 =  y(2:nfreq,2).*conj(y(2:nfreq,1)).*(b(2:nfreq).') + conj(y(2:nfreq,2)).*y(2:nfreq,1).*conj(b(2:nfreq).');
        rk6 = -y(2:nfreq,2).*conj(y(2:nfreq,3)) - y(2:nfreq,3).*conj(y(2:nfreq,2));
        ck6 = 2*abs(y(2:nfreq,2)).^2;
        a = theta(2,:);
        dk6 =  y(2:nfreq,1).*conj(y(2:nfreq,2)).*(a(2:nfreq).') + conj(y(2:nfreq,1).*conj(y(2:nfreq,2)).*(a(2:nfreq).'));
        ik7 = sqrt(-1)*(-y(2:nfreq,1).*conj(y(2:nfreq,2)) + y(2:nfreq,2).*conj(y(2:nfreq,1)));
        ck7 = 2*abs(y(2:nfreq,1)).^2;
        ik8 = sqrt(-1)*(-y(2:nfreq,1).*conj(y(2:nfreq,3)) + y(2:nfreq,3).*conj(y(2:nfreq,1)));
        ck8 = 2*abs(y(2:nfreq,1)).^2;
        dk8 = sqrt(-1)*( -y(2:nfreq,2).*conj(y(2:nfreq,1)).*(b(2:nfreq).') + conj(y(2:nfreq,2).*conj(y(2:nfreq,1)).*(b(2:nfreq).')));
        ik9 = sqrt(-1)*(-y(2:nfreq,2).*conj(y(2:nfreq,3)) + y(2:nfreq,3).*conj(y(2:nfreq,2)));
        ck9 = 2*abs(y(2:nfreq,2)).^2;
        dk9 = sqrt(-1)*( -y(2:nfreq,1).*conj(y(2:nfreq,2)).*(a(2:nfreq).') + conj(y(2:nfreq,1).*conj(y(2:nfreq,2)).*(a(2:nfreq).')));
    
        gr1 = gr1 + xx_r(2:nfreq,:)'*(1-abs(y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,1))) + ...
                    0.5*(xx_r(1,:)'*(1-abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))))+...
                    0.5*(xx_r(end,:)'*(1-abs(y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,1))));
        gr2 = gr2 + xx_r(2:nfreq,:)'*(1 - abs(y(2:nfreq,2)-theta(1,2:nfreq).'.*y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,2))) + ...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,2)-theta(1,1).*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2)))) +...
                    0.5*(xx_r(end,:)'*(1 - abs(y(end,2)-theta(1,end).*y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,2))));  
        gr3 = gr3 + xx_r(2:nfreq,:)'*(1 - abs(y(2:nfreq,3) - theta(2,2:nfreq).'.*y(2:nfreq,1) - theta(3,2:nfreq).'.*y(2:nfreq,2)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,3)))+...
                    0.5*(xx_r(1,:)'*(1 - abs(y(1,3) - theta(2,1).*y(1,1) - theta(3,1).*y(1,2))^2.*exp(-xx_r(1,:)*Beta_1(:,3))))+...
                    0.5*(xx_r(end,:)'*(1 - abs(y(end,3) - theta(2,end).*y(end,1) - theta(3,end).*y(end,2))^2.*exp(-xx_r(end,:)*Beta_1(:,3))));             
        temp_mat_41 = bsxfun(@times, xx_r(2:nfreq,:),rk4);
        temp_mat_42 = bsxfun(@times, ck4, bsxfun(@times, xx_r(2:nfreq,:),xx_r(2:nfreq,:)*Beta_1(:,4)));
        gr4 = gr4 + sum( bsxfun(@times, (temp_mat_41+temp_mat_42), exp(-xx_r(2:nfreq,:)*Beta_1(:,2)) ))' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,4))*xx_r(1,:)')+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(-y(end,1).*conj(y(end,2)) - y(end,2).*conj(y(end,1)))*xx_r(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,4))*xx_r(end,:)');
        temp_mat_51 = bsxfun(@times, xx_r(2:nfreq,:),rk5);
        temp_mat_52 = bsxfun(@times, ck5, bsxfun(@times, xx_r(2:nfreq,:),xx_r(2:nfreq,:)*Beta_1(:,5))); 
        temp_mat_53 = bsxfun(@times, xx_r(2:nfreq,:),dk5);
        gr5 = gr5 + sum( bsxfun(@times, (temp_mat_51 + temp_mat_52 + temp_mat_53), exp(-xx_r(2:nfreq,:)*Beta_1(:,3)) ))'+...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,3)) - y(1,3).*conj(y(1,1)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,5))*xx_r(1,:)'+...
                    exp(-xx_r(1,:)*Beta_1(:,3))*(y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_r(1,:)')+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(-y(end,1).*conj(y(end,3)) - y(end,3).*conj(y(end,1)))*xx_r(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,5))*xx_r(end,:)'+...
                    exp(-xx_r(end,:)*Beta_1(:,3))*(y(end,2).*conj(y(end,1)).*(b(end).') + conj(y(end,2).*conj(y(end,1)).*(b(end).')))*xx_r(end,:)');
        temp_mat_61 = bsxfun(@times, xx_r(2:nfreq,:),rk6);
        temp_mat_62 = bsxfun(@times, ck6, bsxfun(@times, xx_r(2:nfreq,:),xx_r(2:nfreq,:)*Beta_1(:,6))); 
        temp_mat_63 = bsxfun(@times, xx_r(2:nfreq,:),dk6);
        gr6 = gr6 + sum( bsxfun(@times, (temp_mat_61 + temp_mat_62 + temp_mat_63), exp(-xx_r(2:nfreq,:)*Beta_1(:,3)) ))'+...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,2).*conj(y(1,3)) - y(1,3).*conj(y(1,2)))*xx_r(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*(xx_r(1,:)*Beta_1(:,6))*xx_r(1,:)'+...
                    exp(-xx_r(1,:)*Beta_1(:,3))*(y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_r(1,:)')+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(-y(end,2).*conj(y(end,3)) - y(end,3).*conj(y(end,2)))*xx_r(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,2)).^2*(xx_r(end,:)*Beta_1(:,6))*xx_r(end,:)'+...
                    exp(-xx_r(end,:)*Beta_1(:,3))*(y(end,1).*conj(y(end,2)).*(a(end).') + conj(y(end,1).*conj(y(end,2)).*(a(end).')))*xx_r(end,:)');
        temp_mat_71 = bsxfun(@times, ik7, xx_i(2:nfreq,:));
        temp_mat_72 = bsxfun(@times, ck7, bsxfun(@times,xx_i(2:nfreq,:),xx_i(2:nfreq,:)*Beta_2(:,1)));
        gr7 = gr7 + sum( bsxfun(@times, (temp_mat_71 + temp_mat_72), exp(-xx_r(2:nfreq,:)*Beta_1(:,2))))' + ...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(imag(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)')+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(imag(-y(end,1).*conj(y(end,2)) + y(end,2).*conj(y(end,1))))*xx_i(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,1))*xx_i(end,:)');
        temp_mat_81 = bsxfun(@times, ik8, xx_i(2:nfreq,:));
        temp_mat_82 = bsxfun(@times, ck8, bsxfun(@times,xx_i(2:nfreq,:),xx_i(2:nfreq,:)*Beta_2(:,2)));      
        temp_mat_83 = bsxfun(@times, xx_i(2:nfreq,:),dk8);
        gr8 = gr8 + sum( bsxfun(@times, (temp_mat_81 + temp_mat_82 + temp_mat_83), exp(-xx_r(2:nfreq,:)*Beta_1(:,3))))' + ...
                    0.5 * (exp(-xx_r(1,:)*Beta_1(:,3))*(imag(-y(1,1).*conj(y(1,3)) + y(1,3).*conj(y(1,1))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,2))*xx_i(1,:)'+...
                    sqrt(-1)*exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,2)).*(b(1).') + conj(y(1,1).*conj(y(1,2)).*(b(1).')))*xx_i(1,:)')+...
                    0.5 * (exp(-xx_r(end,:)*Beta_1(:,3))*(imag(-y(end,1).*conj(y(end,3)) + y(end,3).*conj(y(end,1))))*xx_i(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,2))*xx_i(end,:)'+...
                    sqrt(-1)*exp(-xx_r(end,:)*Beta_1(:,3))*(-y(end,1).*conj(y(end,2)).*(b(end).') + conj(y(end,1).*conj(y(end,2)).*(b(end).')))*xx_i(end,:)');
        temp_mat_91 = bsxfun(@times, ik9, xx_i(2:nfreq,:));
        temp_mat_92 = bsxfun(@times, ck9, bsxfun(@times,xx_i(2:nfreq,:),xx_i(2:nfreq,:)*Beta_2(:,3)));      
        temp_mat_93 = bsxfun(@times, xx_i(2:nfreq,:),dk9);
        gr9 = gr9 + sum( bsxfun(@times, (temp_mat_91 + temp_mat_92 + temp_mat_93), exp(-xx_r(2:nfreq,:)*Beta_1(:,3))))' + ...
                    0.5 * (exp(-xx_r(1,:)*Beta_1(:,3))*(imag(-y(1,2).*conj(y(1,3)) + y(1,3).*conj(y(1,2))))*xx_i(1,:)' +...
                    exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*(xx_i(1,:)*Beta_2(:,3))*xx_i(1,:)'+...
                    sqrt(-1)*exp(-xx_r(1,:)*Beta_1(:,3))*(-y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_i(1,:)')+...
                    0.5 * (exp(-xx_r(end,:)*Beta_1(:,3))*(imag(-y(end,2).*conj(y(end,3)) + y(end,3).*conj(y(end,2))))*xx_i(end,:)' +...
                    exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,2)).^2*(xx_i(end,:)*Beta_2(:,3))*xx_i(end,:)'+...
                    sqrt(-1)*exp(-xx_r(end,:)*Beta_1(:,3))*(-y(end,1).*conj(y(end,2)).*(a(end).') + conj(y(end,1).*conj(y(end,2)).*(a(end).')))*xx_i(end,:)');
        %%%%%%%%%%%%%%%%%%%
        %hession
        %%%%%%%%%%%%%%%%%%%
        bigmat_h11 = kron(bsxfun(@times, abs(y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,1)), xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h11 = repmat(xx_r(2:nfreq,:), 1,nBeta);
        h11 = h11 + reshape(sum(bsxfun(@times, bigmat_h11, coefmat_h11),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,1))*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(abs(y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,1))*xx_r(end,:)'*xx_r(end,:));
    
        bigmat_h22 = kron(bsxfun(@times,  abs(y(2:nfreq,2)-theta(1,2:nfreq).'.*y(2:nfreq,1)).^2.*exp(-xx_r(2:nfreq,:)*Beta_1(:,2)),xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h22 = repmat(xx_r(2:nfreq,:), 1,nBeta);
        h22 = h22 + reshape(sum(bsxfun(@times, bigmat_h22, coefmat_h22),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,2)-theta(1,1).*y(1,1)).^2.*exp(-xx_r(1,:)*Beta_1(:,2))*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(abs(y(end,2)-theta(1,end).*y(end,1)).^2.*exp(-xx_r(end,:)*Beta_1(:,2))*xx_r(end,:)'*xx_r(end,:));
        
        bigmat_h33 = kron(bsxfun(@times,  abs(y(2:nfreq,3) - theta(2,2:nfreq).'.*y(2:nfreq,1) - theta(3,2:nfreq).'.*y(2:nfreq,2)).^2.*...
                        exp(-xx_r(2:nfreq,:)*Beta_1(:,3)),xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h33 = repmat(xx_r(2:nfreq,:), 1,nBeta);
        h33 = h33 + reshape(sum(bsxfun(@times, bigmat_h33, coefmat_h33),1),nBeta,nBeta) +...
                    0.5*(abs(y(1,3) - theta(2,1).'.*y(1,1) - theta(3,1).'.*y(1,2)).^2.*...
                    exp(-xx_r(1,:)*Beta_1(:,3))*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(abs(y(end,3) - theta(2,end).'.*y(end,1) - theta(3,end).'.*y(end,2)).^2.*...
                    exp(-xx_r(end,:)*Beta_1(:,3))*xx_r(end,:)'*xx_r(end,:));        
        
        bigmat_h44 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck4, xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h44 = repmat(xx_r(2:nfreq,:), 1,nBeta);         
        h44 = h44 + reshape(sum(bsxfun(@times, bigmat_h44, coefmat_h44),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*xx_r(end,:)'*xx_r(end,:));

        bigmat_h55 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck5, xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h55 = repmat(xx_r(2:nfreq,:), 1,nBeta);         
        h55 = h55 + reshape(sum(bsxfun(@times, bigmat_h55, coefmat_h55),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,1)).^2*xx_r(end,:)'*xx_r(end,:));
            
        bigmat_h66 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck6, xx_r(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h66 = repmat(xx_r(2:nfreq,:), 1,nBeta);         
        h66 = h66 + reshape(sum(bsxfun(@times, bigmat_h66, coefmat_h66),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*xx_r(1,:)'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,2)).^2*xx_r(end,:)'*xx_r(end,:));            
                 
        bigmat_h77 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck7, xx_i(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h77 = repmat(xx_i(2:nfreq,:), 1,nBeta);         
        h77 = h77 + reshape(sum(bsxfun(@times, bigmat_h77, coefmat_h77),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*2*abs(y(end,1)).^2*xx_i(end,:)'*xx_i(end,:));
    
        bigmat_h88 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck8, xx_i(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h88 = repmat(xx_i(2:nfreq,:), 1,nBeta);         
        h88 = h88 + reshape(sum(bsxfun(@times, bigmat_h88, coefmat_h88),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,1)).^2*xx_i(1,:)'*xx_i(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,1)).^2*xx_i(end,:)'*xx_i(end,:));     
            
        bigmat_h99 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck9, xx_i(2:nfreq,:)),ones(nBeta,1)');
        coefmat_h99 = repmat(xx_i(2:nfreq,:), 1,nBeta);         
        h99 = h99 + reshape(sum(bsxfun(@times, bigmat_h99, coefmat_h99),1),nBeta,nBeta) +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*2*abs(y(1,2)).^2*xx_i(1,:)'*xx_i(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*2*abs(y(end,2)).^2*xx_i(end,:)'*xx_i(end,:));             
              
        bigmat_h42_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck4.*(xx_r(2:nfreq,:)*Beta_1(:,4)),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h42_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h42_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*rk4, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h42_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        h42 = h42 + reshape(sum(bsxfun(@times, bigmat_h42_1, coefmat_h42_1) +...
                    bsxfun(@times, bigmat_h42_2, coefmat_h42_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,4))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,2)) - y(1,2).*conj(y(1,1)))*xx_r(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,4))*xx_r(end,:)+...
                    (-y(end,1).*conj(y(end,2)) - y(end,2).*conj(y(end,1)))*xx_r(end,:))'*xx_r(end,:));      

        bigmat_h53_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck5.*(xx_r(2:nfreq,:)*Beta_1(:,5)),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h53_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h53_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*rk5, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h53_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h53_3 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*dk5, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h53_3 = repmat(xx_r(2:nfreq,:), 1,nBeta);      
        h53 = h53 + reshape(sum(bsxfun(@times, bigmat_h53_1, coefmat_h53_1) +...
                    bsxfun(@times, bigmat_h53_2, coefmat_h53_2)+...
                    bsxfun(@times, bigmat_h53_3, coefmat_h53_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,1)).^2*(xx_r(1,:)*Beta_1(:,5))*xx_r(1,:)+...
                    (-y(1,1).*conj(y(1,3)) - y(1,3).*conj(y(1,1)))*xx_r(1,:)+...
                    (y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_r(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(2*abs(y(end,1)).^2*(xx_r(end,:)*Beta_1(:,5))*xx_r(end,:)+...
                    (-y(end,1).*conj(y(end,3)) - y(end,3).*conj(y(end,1)))*xx_r(end,:)+...
                    (y(end,2).*conj(y(end,1)).*(b(end).') + conj(y(end,2).*conj(y(end,1)).*(b(end).')))*xx_r(end,:))'*xx_r(end,:));  
 
        bigmat_h56_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,1)).*y(2:nfreq,2),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h56_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h56_2 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,2)).*y(2:nfreq,1),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h56_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        h56 = real(h56 + reshape(sum(bsxfun(@times, bigmat_h56_1, coefmat_h56_1) +...
                        bsxfun(@times, bigmat_h56_2, coefmat_h56_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_r(1,:)+...
                        (conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_r(1,:)))+...
                        0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*((conj(y(end,1)).*y(end,2))*xx_r(end,:)'*xx_r(end,:)+...
                        (conj(y(end,2)).*y(end,1))*xx_r(end,:)'*xx_r(end,:))));     

        bigmat_h59_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,1)).*y(2:nfreq,2),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h59_1 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        bigmat_h59_2 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,2)).*y(2:nfreq,1),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h59_2 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        h59 = imag(h59 + reshape(sum(bsxfun(@times, bigmat_h59_1, coefmat_h59_1) -...
                         bsxfun(@times, bigmat_h59_2, coefmat_h59_2),1),nBeta,nBeta)' +...
                         0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_i(1,:)-...
                         (conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_i(1,:)))+...
                         0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*((conj(y(end,1)).*y(end,2))*xx_r(end,:)'*xx_i(end,:)-...
                         (conj(y(end,2)).*y(end,1))*xx_r(end,:)'*xx_i(end,:))));                      

        bigmat_h63_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck6.*(xx_r(2:nfreq,:)*Beta_1(:,6)),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h63_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h63_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*rk6, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h63_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h63_3 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*dk6, xx_r(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h63_3 = repmat(xx_r(2:nfreq,:), 1,nBeta);      
        h63 = h63 + reshape(sum(bsxfun(@times, bigmat_h63_1, coefmat_h63_1) +...
                    bsxfun(@times, bigmat_h63_2, coefmat_h63_2)+...
                    bsxfun(@times, bigmat_h63_3, coefmat_h63_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,2)).^2*(xx_r(1,:)*Beta_1(:,6))*xx_r(1,:)+...
                    (-y(1,2).*conj(y(1,3)) - y(1,3).*conj(y(1,2)))*xx_r(1,:)+...
                    (y(1,2).*conj(y(1,1)).*(a(1).') + conj(y(1,2).*conj(y(1,1)).*(a(1).')))*xx_r(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(2*abs(y(end,2)).^2*(xx_r(end,:)*Beta_1(:,6))*xx_r(end,:)+...
                    (-y(end,2).*conj(y(end,3)) - y(end,3).*conj(y(end,2)))*xx_r(end,:)+...
                    (y(end,2).*conj(y(end,1)).*(a(end).') + conj(y(end,2).*conj(y(end,1)).*(a(end).')))*xx_r(end,:))'*xx_r(end,:));                  

        bigmat_h68_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,2)).*y(2:nfreq,1),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h68_1 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        bigmat_h68_2 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,1)).*y(2:nfreq,2),...
                        xx_r(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h68_2 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        h68 = imag(h68 + reshape(sum(bsxfun(@times, bigmat_h68_1, coefmat_h68_1) -...
                        bsxfun(@times, bigmat_h68_2, coefmat_h68_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,2)).*y(1,1))*xx_r(1,:)'*xx_i(1,:)-...
                        (conj(y(1,1)).*y(1,2))*xx_r(1,:)'*xx_i(1,:)))+...
                        0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*((conj(y(end,2)).*y(end,1))*xx_r(end,:)'*xx_i(end,:)-...
                        (conj(y(end,1)).*y(end,2))*xx_r(end,:)'*xx_i(end,:))));    
                 
        bigmat_h72_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ck7.*(xx_i(2:nfreq,:)*Beta_2(:,1)),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');                
        coefmat_h72_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h72_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,2)).*ik7, xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h72_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        h72 = h72 + reshape(sum(bsxfun(@times, bigmat_h72_1, coefmat_h72_1) +...
                    bsxfun(@times, bigmat_h72_2, coefmat_h72_2),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,2))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,1))*xx_i(1,:)+...
                    imag(-y(1,1).*conj(y(1,2)) + y(1,2).*conj(y(1,1)))*xx_i(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,2))*(2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,1))*xx_i(end,:)+...
                    imag(-y(end,1).*conj(y(end,2)) + y(end,2).*conj(y(end,1)))*xx_i(end,:))'*xx_r(end,:));     
    
        bigmat_h83_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck8.*(xx_i(2:nfreq,:)*Beta_2(:,2)),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h83_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h83_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ik8, xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h83_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h83_3 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*(dk8), xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h83_3 = repmat(xx_r(2:nfreq,:), 1,nBeta);      
        h83 = h83 + reshape(sum(bsxfun(@times, bigmat_h83_1, coefmat_h83_1) +...
                    bsxfun(@times, bigmat_h83_2, coefmat_h83_2)+...
                    bsxfun(@times, bigmat_h83_3, coefmat_h83_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,1)).^2*(xx_i(1,:)*Beta_2(:,2))*xx_i(1,:)+...
                    (-y(1,1).*conj(y(1,3)) + y(1,3).*conj(y(1,1)))*xx_i(1,:)+...
                    imag(-y(1,2).*conj(y(1,1)).*(b(1).') + conj(y(1,2).*conj(y(1,1)).*(b(1).')))*xx_i(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(2*abs(y(end,1)).^2*(xx_i(end,:)*Beta_2(:,2))*xx_i(end,:)+...
                    (-y(end,1).*conj(y(end,3)) + y(end,3).*conj(y(end,1)))*xx_i(end,:)+...
                    imag(-y(end,2).*conj(y(end,1)).*(b(end).') + conj(y(end,2).*conj(y(end,1)).*(b(end).')))*xx_i(end,:))'*xx_r(end,:));           

        bigmat_h93_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ck9.*(xx_i(2:nfreq,:)*Beta_2(:,3)),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h93_1 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h93_2 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*ik9, xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h93_2 = repmat(xx_r(2:nfreq,:), 1,nBeta);  
        bigmat_h93_3 = kron(bsxfun(@times,exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*(dk9), xx_i(2:nfreq,:)), ones(nBeta,1)');
        coefmat_h93_3 = repmat(xx_r(2:nfreq,:), 1,nBeta);      
        h93 = h93 + reshape(sum(bsxfun(@times, bigmat_h93_1, coefmat_h93_1) +...
                    bsxfun(@times, bigmat_h93_2, coefmat_h93_2)+...
                    bsxfun(@times, bigmat_h93_3, coefmat_h93_3),1),nBeta,nBeta)' +...
                    0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*(2*abs(y(1,2)).^2*(xx_i(1,:)*Beta_2(:,3))*xx_i(1,:)+...
                    (-y(1,2).*conj(y(1,3)) + y(1,3).*conj(y(1,2)))*xx_i(1,:)+...
                    imag(-y(1,1).*conj(y(1,2)).*(a(1).') + conj(y(1,1).*conj(y(1,2)).*(a(1).')))*xx_i(1,:))'*xx_r(1,:))+...
                    0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*(2*abs(y(end,2)).^2*(xx_i(end,:)*Beta_2(:,3))*xx_i(end,:)+...
                    (-y(end,2).*conj(y(end,3)) + y(end,3).*conj(y(end,2)))*xx_i(end,:)+...
                    imag(-y(end,1).*conj(y(end,2)).*(a(end).') + conj(y(end,1).*conj(y(end,2)).*(a(end).')))*xx_i(end,:))'*xx_r(end,:));     

        bigmat_h98_1 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,1)).*y(2:nfreq,2),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h98_1 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        bigmat_h98_2 = kron(bsxfun(@times, exp(-xx_r(2:nfreq,:)*Beta_1(:,3)).*conj(y(2:nfreq,2)).*y(2:nfreq,1),...
                        xx_i(2:nfreq,:)), ones(nBeta,1)');     
        coefmat_h98_2 = repmat(xx_i(2:nfreq,:), 1,nBeta);  
        h98 = real(h98 + reshape(sum(bsxfun(@times, bigmat_h98_1, coefmat_h98_1) +...
                        bsxfun(@times, bigmat_h98_2, coefmat_h98_2),1),nBeta,nBeta)' +...
                        0.5*(exp(-xx_r(1,:)*Beta_1(:,3))*((conj(y(1,1)).*y(1,2))*xx_i(1,:)'*xx_i(1,:)+...
                        (conj(y(1,2)).*y(1,1))*xx_i(1,:)'*xx_i(1,:)))+...
                        0.5*(exp(-xx_r(end,:)*Beta_1(:,3))*((conj(y(end,1)).*y(end,2))*xx_i(end,:)'*xx_i(end,:)+...
                        (conj(y(end,2)).*y(end,1))*xx_i(end,:)'*xx_i(end,:))));   
        h24=h42'; h35=h53'; h65=h56'; h95=h59'; h36=h63';
        h86=h68'; h27=h72'; h38=h83'; h39=h93'; h89=h98';
    end
    ze = zeros(nBeta,nBeta);
    h1 = [h11,repmat(ze,1,8)];
    h2 = [ze,h22,ze,-h24,ze,ze,-h27,ze,ze];
    h3 = [ze,ze,h33,ze,-h35,-h36,ze,-h38,-h39];
    h4 = [ze,-h42,ze,h44,repmat(ze,1,5)];  
    h5 = [ze,ze,-h53,ze,h55,h56,ze,ze,h59];
    h6 = [ze,ze,-h63,ze,h65,h66,ze,h68,ze];
    h7 = [ze,-h72,ze,ze,ze,ze,h77,ze,ze];
    h8 = [ze,ze,-h83,ze,ze,h86,ze,h88,h89];
    h9 = [ze,ze,-h93,ze,h95,ze,ze,h98,h99];

    gr = [gr1;gr2;gr3;gr4;gr5;gr6;gr7;gr8;gr9]; h = [h1;h2;h3;h4;h5;h6;h7;h8;h9]; f = -f;
    gr_index = (1:(dimen^2*nBeta)).*kron(chol_index(Phi_temp,:),ones(nBeta,1)');
    gr_index = gr_index(find(gr_index~=0));
    gr = gr(gr_index); h = h(gr_index,gr_index);
end    